### ISSUE TITLE
Usage trough multiple pages

### ISSUE THREAD

**Issue by nikolacrnicrni** [RickStrahl/Westwind.Globalization#101]
I have tested everything and it all works well, but I have the following issue:
When I choose language from the dropdown, it converts it as it should, but when I open the next page it all resets. 
How to mantain the selected language?
Should I use cookies?

Thanks

**Comment by demirsefa** [comment]
I use session inside Application_AcquireRequestState function and it works.
The code like this 
`string lang = (String)HttpContext.Current.Session["culture"];
WebUtils.SetUserLocale(culture: lang, allowedLocales: "en,tr,ar");
`

**Comment by nikolacrnicrni** [comment]
Can you explan how to send selected language from dropdown to Application_AcquireRequestState function and usage of that code? 

Thanks

**Comment by demirsefa** [comment]
I didnt use session in layout.cshtml.I just handle with session without request.params 
When I select language from html
`<a class="languageLink @if (lang == "tr") {@("languageActive")}" href="@Url.Action("ChangeCulture", "Pages", new { Lang="tr", returnUrl = this.Request.RawUrl })"><img class="languageImage" src="/images/icons/tr.png" /> Türkçe</a>`
And then ChangeCulture action 
` public ActionResult ChangeCulture(string lang)
        {
            Session["locale"] = lang;
            return Redirect(Request.UrlReferrer.ToString());
        }
`
So every request  we check  session.if session and Session["locale"] not null we set language by using webutils.

if you want to use requst.params you dont need session.You can just check which language user prefence from params.

I hope it works.

**Comment by RickStrahl** [comment]
You can also use _ViewStart.cshtml for this sort of thing. Always a bad idea to use _Layout.cshtml because it's not actually running before the content page - the content page loads the layout page.
