### ISSUE TITLE
Using WebUtils.SetUserLocale() on _Layout.cshtml to work on all views

### ISSUE THREAD

**Issue by nikolacrnicrni** [RickStrahl/Westwind.Globalization#102]
On the _Layout.cshtml I put between "head" tags code below

```
@{
    var localeId = Request.Params["LocaleId"];

    if (!string.IsNullOrEmpty(localeId))
    {
        WebUtils.SetUserLocale(localeId, localeId, "$", true, "en, sr, hr, bs");
    }
}
```
And in that layout I set translation for menu options like Home, About etc.

```
            <li>@Html.ActionLink(DbRes.T("Home", "Meni"), "Index", "Home")</li>
            <li>@Html.ActionLink(DbRes.T("About", "Meni"), "About", "Home")</li>
            <li>@Html.ActionLink(DbRes.T("Contact", "Meni"), "Contact", "Home")</li>

```
It all works for the shared layout part. But when I insert DbRes.T() in Index.cshtml that is @RenderBody(), it can't translate that part. Only way it works is if I copy/paste this code of _Layout.cshtml in every view individually.

Is there a way just to set  WebUtils.SetUserLocale() once in _Layout and it can work when I change language in @RenderBody()?

**Comment by RickStrahl** [comment]
it's not a good idea to do this in the layout or any other part of the MVC eco system as all that happens pretty late in the ASP.NET pipeline. Set this in `Application_BeginRequest()` in global.asax to guarantee the locale is applied through the entire request pipeline.

If you really need to do this in MVC I suggest using an ActionFilter and `OnActionExecuting` or you can also see about putting it in `_ViewStart.cshtml`.
