### ISSUE TITLE
Restrict access to Invariant (default) resources

### ISSUE THREAD

**Issue by craigvn** [RickStrahl/Westwind.Globalization#104]
We would like to allow our editors access to change the resources for specific resources, ie Spanish, but we don't want them to be able to change the Invariant default resource that we created. Is there a way to set this up?

Thanks

**Comment by RickStrahl** [comment]
There's nothing built in to lock resources - you would have to add that yourself. That's too specific of a scenario to provide out of box.

If you did this yourself you'd probably have to add a field that determines lock status, and then check the lock status on any updates.
