### ISSUE TITLE
Add DeepL as translation option

### ISSUE THREAD

**Issue by twenzel** [RickStrahl/Westwind.Globalization#105]
Please use the https://www.deepl.com/translator as third translation option. This translator is way better than any other current translators.

**Comment by RickStrahl** [comment]
Is there some sort of API to get at the data? Without that we can't integrate with it.

**Comment by RickStrahl** [comment]
Ok did a little experimenting and figured out how to access their translation API. Heck it's hard to even see if they are selling any services at all. Not sure how they make any money :-) Not sure what the legality of this is, but it works without any special tokens or authentication.

2be67d3e47898bb37935fe62de711e2480956645

**Comment by twenzel** [comment]
Awesome!

**Comment by ponchautf** [comment]
Hi,

Could you update your DeepL Implementation?
DeepL API is not free anymore and require a Auth_Key.
Documentation can be found here : https://www.deepl.com/api.html
