### ISSUE TITLE
Error when updating Westwind.Utilities

### ISSUE THREAD

**Issue by geirsagberg** [RickStrahl/Westwind.Globalization#106]
After updating Westwind.Utilities in a project using Westwind.Globalization, I get the error:

```
[MissingMethodException: Method not found: 'System.Type Westwind.Utilities.ReflectionUtils.GetTypeFromName(System.String)'.]
   Westwind.Web.ScriptCompressionModule.PostResolveRequestCache(Object sender, EventArgs e) +0
```

This is probably due to changing the signature of `GetTypeFromName` in https://github.com/RickStrahl/Westwind.Utilities/commit/7d8d85aab109b5a23067899204275f0cb7932e64#diff-f562382ebc25ea7ee3efb39a3c3381d2.

When you change the signature of a method (even just adding an optional parameter), that is a breaking change, and should warrant a major version bump. I know this because I have done the same mistake :)

**Comment by RickStrahl** [comment]
What versions are the assemblies (WWG and WWU)? I think I fixed this with an update that had overloads for the old signature.

**Comment by RickStrahl** [comment]
Double checked and that change wasn't actually made - added overload without the second parameter and removed the optional parameter on the new method. This should make the old one still work.

The reason I asked about versions - the set with Westwind.Globalization should have been working - adding a newer copy of Westwind.Utilities is likely what broke?

**Comment by geirsagberg** [comment]
The error appeared using WWG 2.1.5 and WWU 3.0.8. As a workaround, downgrading to 3.0.1 fixed it.

Thanks for the quick update, I'll check out 3.0.9 after the holidays :) feel free to close this issue.

**Comment by geirsagberg** [comment]
Works with 3.0.9, closing.
