### ISSUE TITLE
Local resource set on MVC

### ISSUE THREAD

**Issue by Bartmax** [RickStrahl/Westwind.Globalization#11]
Is it possible to have a Local Resource set on MVC where there's no .aspx file extension ?

So you have a resource set like /Home/Index ?

if that's not possible, is there anyway to set the Default resource set when none is found like:
defaultResourceSet = "General" ?

**Comment by RickStrahl** [comment]
Sure you can name your resource sets anything you want. Just remember that you have to type it out that way when you use the resources when you specify the resource set. And if you create strongly typed resources the names will be pretty ugly if you do that.

Generally I prefer to use resource sets for 'features' - so I tend to go by Controller more than by page. You have Home and Account resourcesets rather than a home_index resource set.

As to default - there's no default, but you can use "" or null.

**Comment by Bartmax** [comment]
Sorry, that was really confusing on my part.

When working with ```addMissingResources="true" ```

Right now, when you use ```DbRes.T("Something")``` on an .aspx file, you get a resource set created called like 'localizationadmin/localizationadmin.aspx' but that "feature" only works on .aspx files.

What I was asking, if I can have this same behavior on MVC (not .aspx files) so it gets the information from route data so it auto creates a resource set like Home/Index and inside that view I can use  ```DbRes.T("Something")```

If I do this right now, the resource set created is "" (String.Empty). When I go to resource editor, all this translations are saved into a String.Empty resource set in the same place, so I must specify the resource set on MVC view, so instead of doing  ```DbRes.T("Something")``` I must do  ```DbRes.T("Something", "Home")``` 

What I was wondering, if 

a) is there anyway to make the same behavior of .aspx files with MVC using maybe route data.
b) if not, is there anyway to specify a specific resource set for not provided one so instead of a resource set of String.Empty is created, I can name it something like General.

What I'm trying to avoid is to provide a resource set name in all the calls to DbRes.T("Something", "General")

the Documentation on ```public static string T(string resId, string resourceSet = null, string lang = null);``` says: 

```
        //   resourceSet:
        //     Name of the ResourceSet that houses this resource. If null or empty resources
        //     are used.
```

but I'm getting String.Empty resourceset. so I'm not sure what "resources are used" means on that doc.
