### ISSUE TITLE
Localize DataAnnotations

### ISSUE THREAD

**Issue by mtugnoli** [RickStrahl/Westwind.Globalization#112]
Is it possible to localize also DataAnnotations ?

ex. Name and ErrorMessage 

[Display(Name = "Confirm password")]
[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]

**Comment by RickStrahl** [comment]
Sure. In ASP.NET Core attributes are localized using their model type as the resource set name and the resource id specified as the **ErrorMessage**:

![image](https://user-images.githubusercontent.com/1374013/35710271-bfc04ed6-075a-11e8-9674-9e8e70b77a0d.png)
