### ISSUE TITLE
Globalization and Iframes

### ISSUE THREAD

**Issue by mtugnoli** [RickStrahl/Westwind.Globalization#113]
I just testing Westwind.Globalization in my new .net core 2 project
in this project when user logon is set Thread.CurrentThread.CurrentCulture and Thread.CurrentThread.CurrentUICulture with user culture (it-IT).
but when load an iframe inside this the culture is en-US.
so a part of project is globalize in Italian and another part in English.
Any Idea ?

**Comment by RickStrahl** [comment]
The new ASP.NET Core auth system doesn't change the thread's culture but relies entirely on dependency injection to get access to the localizers. If you change the thread culture it'll have no affect on the localization of the string localizers.

If you're loading things into a frame you're loading things on a completely separate request so depending on where the request loaded from the behavior will rely on that location.

**Comment by RickStrahl** [comment]
Doesn't matter an iFrame is still a separate request. You need to run that request through the same pipeline as the main page to get the same localization functionality. Like I said the StringLocalizer totally ignore thread and default culture settings and get everything they need from DI. You can change the thread culture until you're blue in the face it's not going to change the way the string localizer localizes.
