### ISSUE TITLE
HTML Text

### ISSUE THREAD

**Issue by Bartmax** [RickStrahl/Westwind.Globalization#12]
Is there any way to add HTML string for content localization ?
Like: 
```
<p>some content that needs <b>to be localized</b></p>
<p>this content is HTML <a href="google.com">Click here</a></p>
```

**Comment by RickStrahl** [comment]
Not sure I understand the question. This is server side localization so you need to embed the resource as a resource expression in one of the formats support.

**Comment by Bartmax** [comment]
I have a part of a page that needs to be localized. that part may contains html code (like <b> or <br>) inside the content.

I couldn't get to localize content with HTML tags on it. Via the resource editor a potentially danger bla bla bla request and when edited the database directly i get the encoded string.

in a simple example, let's say I want to render my view as :

<ul>
<li>First</li>
<li>Second</li>
<li>Third <b> and last</li>
</ul>

If I want to localize that I can do this:

<ul>
<li>@DbRes.T("First")</li>
<li>@DbRes.T("Second")</li>
<li>@DbRes.T("Third") <b> @DbRes.T("and last")</li>
</ul>

but I want to do this :
<ul>
@DbRes.T("LocalizedList")
</ul>

This is not the ideal example but I hope you get the point.

Currently I'm doing @Html.Raw(DbRes.T("LocalizedList")) which works fine. I want to know if there are some way to enable html on the resource editor or a built in way to tell the DbRes helper that it is a HTML string.

**Comment by RickStrahl** [comment]
Not currently but that's a good suggestion. I'll add a DbRes.THtml function:

```C#
/// <summary>
/// Localization helper function that Translates a resource
/// Id to a resource value to an HtmlStringg. Easy access that allows full
/// control over the resource to retrieve or default UiCulture
/// locale retrieval.
/// 
/// Use this version for HTML content that needs to be embedded in Razor
/// views or other server tools that can use pre-encoded HTML content.
/// </summary>
/// <param name="resId">The Resource Id to retrieve
/// Note resource Ids can be *any* string and if no
/// matching resource is found the id is returned.
/// </param>
/// <param name="resourceSet">Name of the ResourceSet that houses this resource. If null or empty resources are used.</param>
/// <param name="lang">5 letter or 2 letter language ieetf code: en-US, de-DE or en, de etc.</param>
/// <returns>
/// Localized resource or the resource Id if no match is found. 
/// This value *always* returns a string unless you pass in null.
/// </returns>
public static HtmlString THtml(string resId, string resourceSet = null, string lang = null)
{
    return new HtmlString( T(resId,resourceSet,lang) );
}
```

**Comment by RickStrahl** [comment]
Checked into the latest Dev branch updates.
