### ISSUE TITLE
Build unsuccessful on cloning the project

### ISSUE THREAD

**Issue by kishorekumardv** [RickStrahl/Westwind.Globalization#125]
Hi,

First of all thanks for making the project and a fantastic walk through video! The project suits my needs but I've to make a few customizations (like change connection to Oracle database, I want the DB connection through a service layer, removing .Net core packages as my application is legacy webforms etc). The Westwind.Globalization project doesn't load in VS2015 and when I load the solution(net45) in VS2017 the project doesn't build. Am I missing anything?

![image](https://user-images.githubusercontent.com/6365420/38583256-71132d10-3ce0-11e8-83ae-c89ffea20b1f.png)

**Comment by RickStrahl** [comment]
Looks like you're missing a reference to Westwind.Utilities which is a dependency of all the packages. Did you remove this? If you did you have to add it back in.

**Comment by kishorekumardv** [comment]
I haven’t removed any references and don’t find the Utilities reference in the project. All I did is clone from the git url and build.
