### ISSUE TITLE
AspNetCore Angular project template

### ISSUE THREAD

**Issue by Avareto** [RickStrahl/Westwind.Globalization#129]
Hi Rick!
Any idea how I get it to work with the AspNetCore Angular project template? 
When I type ~/LocalizationAdmin/ the client falls back to the root url, because Angular doesn’t know it and redirects to the default route.

Andreas

**Comment by RickStrahl** [comment]
Explicitly use ~/LocalizationAdmin/index.html. Otherwise you have to explictly map a route **before** the client side routes are handled on the server.
