### ISSUE TITLE
Add DeepL V2 translation API

### ISSUE THREAD

**Issue by ponchautf** [RickStrahl/Westwind.Globalization#148]
Hi,

Could you please add the new DeepL API?
DeepL is not free anymore and require and API key. 

It would be nice if you can add this to your package.
more info about this API : https://www.deepl.com/api.html 

Thanks.

**Comment by RickStrahl** [comment]
Well they went to a pay model **and** apparently you can only get an account if you have a credit card in the EU. I can't even set up a test account, so that puts me out of the running...

If somebody has an account they want to share I'd be happy to look into hooking support back up.
