### ISSUE TITLE
.net core 3.0 support

### ISSUE THREAD

**Issue by anisite** [RickStrahl/Westwind.Globalization#155]
Hi, 
in .net core 3.0 this method : 
`Microsoft.AspNetCore.Mvc.Controller.Json(System.Object, Newtonsoft.Json.JsonSerializerSettings) `
not exist anymore that cause westwind to crash and usable. Any solution ?

**Comment by RickStrahl** [comment]
I think you need to add:

```cs
services.AddMvc()
                .AddNewtonsoftJson();
```

And explicitly add the Newtonsoft.Json package since this was removed from .NET Core 3.0 in favor of a new built-in (and much more limited) serializer.

**Comment by anisite** [comment]
Hi, thank you for your time. I will try with 3.0-preview5 tomorrow.
