### ISSUE TITLE
Namespace Support

### ISSUE THREAD

**Issue by bliles** [RickStrahl/Westwind.Globalization#160]
The project appears to assume that all ResourceSets are in the same namespace. What do you think would be involved in supporting namespaces for ResourceSets?

**Comment by RickStrahl** [comment]
Not sure exactly what you're referring to here. 

Output generation and imports are for a single namespace yes. Not sure how we could fix that without making things a lot more complicated by requiring namespaces inside of the resource file itself.

**Comment by bliles** [comment]
Yes, I agree with what you're saying. Originally we had separated out a variety of resources into different namespaces, but for the sake of making a UI to make it easy for our translators to translate our app, we moved everything that needs translation into the same namespace and it's fine.
