### ISSUE TITLE
How to use this project (Westwind.Globalization) for NON-MVC projects?

### ISSUE THREAD

**Issue by citybear01** [RickStrahl/Westwind.Globalization#17]
Rick,

I am a newbie to VISUAL STUDIO 2013 and .NET programming.  Unfortunately, nearly all of our code here at my company was made before MVC.  So, how do I integrate your code in with existing non-MVC projects?

**Comment by RickStrahl** [comment]
It'll work just fine with classic WebForms or even an empty Web site.

Good starting points might be old articles that discuss localization in general:
http://www.west-wind.com/presentations/wwdbResourceProvider/introtolocalization.aspx

And then specifically using a custom resource provider like Westwind.Globalization:
http://www.west-wind.com/presentations/wwdbResourceProvider/

Note: the library had a different name back then but the same concepts apply to the newer versions. Basically for WebForms you typically want to use meta:resources assigned to properties on various controls as well as Context.GetLocalResourceObject/GetGlobalResourceObject.
