### ISSUE TITLE
Reloading cache using an API call

### ISSUE THREAD

**Issue by azharmahmood** [RickStrahl/Westwind.Globalization#172]
Is it possible to reload cache using a Dll method call, this is required to reload cache on multiple servers in a web farm environment.

**Comment by azharmahmood** [comment]
Hi Rick, any guidance or pointers on this question?

**Comment by azharmahmood** [comment]
I think I found the call.

 Westwind.Globalization.DbRes.ClearResources();

**Comment by RickStrahl** [comment]
Did that work for you?
