### ISSUE TITLE
Westwind.Globalization\Resources\localize.png is no embedded resource

### ISSUE THREAD

**Issue by StefanBuecherl** [RickStrahl/Westwind.Globalization#20]
Hello, 

Westwind.Globalization\Resources\localize.png is no embedded resource. So the WebResource.axd cannot display it.

I fixed that for myself but it would be nice if it will be included in future commits.

Thanks!

Best regards,

Stefan

**Comment by RickStrahl** [comment]
Where is this image referenced? In the latest beta versions? 

I've removed all the embedded images and instead rely on CSS and links to the LocalizationAdmin resources that are installed into a Web project.

If you're talking about older versions - those won't be updated any further, so your fix should be good to go if you're sticking to the older version.

**Comment by StefanBuecherl** [comment]
No it is not the latest beta. But then it is ok.

Thanks for your quick reply!
Am 06.05.2015 19:11 schrieb "Rick Strahl" <notifications@github.com>:
