### ISSUE TITLE
.Net 5

### ISSUE THREAD

**Issue by davidhendrickmb** [RickStrahl/Westwind.Globalization#206]
Hi there,
I was wondering if this package is fully compatible with .Net 5 or if that's on the way?
Thanks,
David

**Comment by RickStrahl** [comment]
Should work as is as .NET 5.0 can use 3.1 components.

**Comment by RickStrahl** [comment]
Actually just realized that I have been using it in .NET 5.0 app for a while. The 3.1 version works fine in .NET 5.0. When I get a minute I'll update the target list. I don't think there are any changes required to retarget explicitly for `Net5.0`, but the `netcoreapp3.1` definitely works.
