### ISSUE TITLE
Use in Non-MVC ASP.NET project

### ISSUE THREAD

**Issue by citybear01** [RickStrahl/Westwind.Globalization#23]
I installed your package inside a non-MVC ASP.NET project.  When I navigate to the Localization Admin, I get a whole bunch of JAVA errors.  I am using Visual Studio 2013 and using IE 8.

I put in the Web.CONFIG file changes as you indicated.  How do I get the Localization Admin page to show?

BTW, I am newbie here.

Any help would be appreciated!

Thank you!

**Comment by RickStrahl** [comment]
IE 8 is not supported for the administration interface. You need to use a more modern browser - IE9 forward will work. If you're on XP I suggest installing Chrome or FireFox.
