### ISSUE TITLE
Asian language support

### ISSUE THREAD

**Issue by citybear01** [RickStrahl/Westwind.Globalization#24]
Does this product provide support for languages that read from the right to the left like Chinese, Arabic, or Hebrew?

If so, how can I trigger that?

If not, how would you suggest that this be done?

**Comment by RickStrahl** [comment]
Can you be more specific what you're worried about? 

You should be able to get the languages in there just as plain text. As long as the database can accept the right character set for your captured text this should just work as is.

**Comment by citybear01** [comment]
In the LocalizationAdmin page and where you enter the actual text for the item you have selected to translate, the text box field needs to be able to enter text from the right.  So, text entry should be determined based on Language.  Most languages are left to right.  However, a few (Chinese, Japanese, Hebrew, Arabic) are right to left.  So, if somebody is entering Hebrew for example, the actual text box to enter the translated value would need to be set to receive the text in this direction (right to left).  To programmatically do this see this StackOverflow references:

http://stackoverflow.com/questions/17462075/right-to-left-typing-in-text-box

http://stackoverflow.com/questions/7524855/right-to-left-text-html-input

http://stackoverflow.com/questions/5527030/asp-net-textbox-right-to-left

**Comment by RickStrahl** [comment]
Right - you can switch the `dir="rtl"` in the `html` or `body` tag to switch the entire page.

However, that's not really the responsibility of the provider/manager, that has to be done as part of the application. The resource admin form only works with two localized languages right now (English and German) so it makes no

I guess I'm not quite sure what you're asking. If you need to work with rtl in your interface you switch the entire form into rtl by doing:

```html
<body dir="rtl">
```

I'm not sure how you would expect this to work 'automatically'.

**Comment by RickStrahl** [comment]
Added support for RTL editing for localeIds that require RTL. 

Addressed in  4a233bbc00db7ec3551d99e93dc6eb5e65371446
