### ISSUE TITLE
Abend with FireFox

### ISSUE THREAD

**Issue by citybear01** [RickStrahl/Westwind.Globalization#25]
Per your suggestion, I am using FireFox instead of IE 8 to execute my application.  I am now getting an abend 
"Make sure data column names are correct"
"Make sure the index is not a negative number."
"Make sure that the maximum index on a list is less than the list size"

![abend with firefox](https://cloud.githubusercontent.com/assets/5047040/7779819/ff8e1be2-00a5-11e5-8cd2-e3ec03c483b2.jpg)

**Comment by RickStrahl** [comment]
This error is normal if you haven't configured the provider, or haven't created a table yet or there is no data at all in the localization table (seems like the last thing is the issue based on the error you're seeing). You will need at least one resource in the resource table (when the table is created it creates some sample resources - it looks like you may have deleted those).

Don't run in Debug mode unless you are actually debugging - just run the app. The service API will fail and push the errors back into the client. You should see an error in the UI that tells you that the table doesn't exist. Then create it.

Please take a look at the Installation guide or the video to see how to get started.

**Comment by citybear01** [comment]
You are correct.  I dropped the table and then restarted the application.  I navigated to the LocalizationAdmin and I saw the option to "Create Table".  Once I did that, the application worked.

**Comment by citybear01** [comment]
You are correct.  I dropped the table and then restarted the application.  I navigated to the LocalizationAdmin and I saw the option to "Create Table".  Once I did that, the application worked.
