### ISSUE TITLE
Problems with instructions in section: Using the ASP.NET Resource Provider

### ISSUE THREAD

**Issue by citybear01** [RickStrahl/Westwind.Globalization#27]
I have an existing WebForm application that uses meta:xxxxx tags in the HTML.  So, I followed the instructions you listed in the section labeled "Using the ASP.NET Resource Provider".  Now I am getting an error when I start up the application.  Below are pictures of the Error screen that appears when the application starts up and the second is a "listing" of my Web Config file

![webconfig file error when switching to support using the asp net resource provider](https://cloud.githubusercontent.com/assets/5047040/7814164/528bd1c8-038e-11e5-8e46-950884d7ef5e.jpg)

Web Config file:

![web config file](https://cloud.githubusercontent.com/assets/5047040/7814175/5fc6cfe6-038e-11e5-88a9-132e9eea4611.jpg)

**Comment by citybear01** [comment]
I also discovered that when I went to the Designer page within my Visual Studio 2013 tab, I was getting these errors as well:

![visual studio designer page error](https://cloud.githubusercontent.com/assets/5047040/7817652/44d94068-03a4-11e5-9e14-34637188aa36.jpg)

**Comment by RickStrahl** [comment]
This library requires .NET 4.5. I think you may be running .NET 4.0 and so the assembly either wasn't added to your project or if it was it's not usable because it's the wrong version.

**Comment by citybear01** [comment]
I am using .NET 4.5.1:

![project framework page](https://cloud.githubusercontent.com/assets/5047040/7821262/98199752-03bb-11e5-91c2-f1722cbee31a.jpg)

**Comment by RickStrahl** [comment]
Oh I see the problem. Old project upgraded from 1.x yes?

The assembly for the factory is `Westwind.Globalization.Web`. Change in the configuration setting.

**Comment by citybear01** [comment]
This was a brand new project built initially for 4.5.1.  So, it was not an old project upgraded.
I made those changes to the Web Config file and I get the same error:

Here is the Designer Page within VS 2013:

![try 02 designer page](https://cloud.githubusercontent.com/assets/5047040/7823338/c5e7fae0-03c8-11e5-8411-d22e4f78a31a.jpg)

Here is the Source for the Designer Page (HTML):

![try02 html version of designer page](https://cloud.githubusercontent.com/assets/5047040/7823342/d6a5792a-03c8-11e5-8218-fe751fcb9f49.jpg)

Here is the revised WebConfig File:

![try02 webconfig file](https://cloud.githubusercontent.com/assets/5047040/7823349/e56edea6-03c8-11e5-8d65-7a1d4480acbd.jpg)

As you can see I am still getting those errors in the Designer.

==> Note, I am able to bring up the page in FireFox <==
==> But I am NOT getting the Meta tags resolved     <==

Here is a sample line from the HTML:

==>  <asp:Label ID="lblAmount" runat="server" Text="" meta:resourcekey="lblAmountResource1"></asp:Label> <==

Here is a screen of this definition using LocalizationAdmin:
For lblAmountResource1, here is the entry:

![try02 localizationadmin page](https://cloud.githubusercontent.com/assets/5047040/7823440/816d231c-03c9-11e5-9e8f-a8ff5faccc14.jpg)

**Comment by citybear01** [comment]
It looks like the line that I tried to isolate for you did not come out the way I expected.

If you look at the HTML it is line 11 or this text:

"<asp:Label ID="lblAmount" runat="server" Text="" meta:resourcekey="lblAmountResource1"></asp:Label>"

The meta:resourcekey is this:

" meta:resourcekey="lblAmountResource1""

**Comment by citybear01** [comment]
Looks like my attempt at posting the actual HTML failed again.  So, here is a JPEG for that line:

![try02 isolated html](https://cloud.githubusercontent.com/assets/5047040/7823538/24289a78-03ca-11e5-81cc-cfa3ac82f089.jpg)

**Comment by RickStrahl** [comment]
I'm not sure...

Can you try this for a sanity check:

* create a new empty web project
* add the Westwind.Globalization.Web Nuget
* Compile
* Add a connection string to the config
* Create the localization table

Then open the ResourceTest.aspx page. There are a couple of controls in that page. Do those show up correctly? They do for me.

One thing I see in your install is that the versions are not the latest. There was a bug in the previous release that caused issues with WebForms controls and that was fixed in the latest package. Westwind.Utilities should be V2.64. You can also try updating all the assemblies:

From the Package Manager Console:

```
Update-Package Westwind.Globalization.Web
```

I think this will update all the dependencies. If not at the very least update Westwind.Utilities as well - it should be 2.64 on the latest rev.

My guess is for some reason or other your various assembly versions are out of sync causing assembly load errors.

**Comment by citybear01** [comment]
OK, did what you asked:

Created a new empty web project:

![try 03 new project definition](https://cloud.githubusercontent.com/assets/5047040/7824213/327e1508-03cf-11e5-9ce3-8a5a64b7e188.jpg)


Here is the NuGet Console stuff:

![try 03 nuget console stuff](https://cloud.githubusercontent.com/assets/5047040/7824226/4e431360-03cf-11e5-9a79-d977a8fa79bc.jpg)


I then tried ResourceTest.aspx and it worked fine.

Tomorrow, I will add my Master Page, Default Page, and remaining code.

And I will try again!

I will let you know.

One final question.  Please keep in mind that I am newbie to Visual Studio and .NET.  This is my first project and I was a IBM Mainframer up until April.

If I use a meta:resourcekey tag in the HTML, and I change cultures, do I have to explicitly in the code behind obtain the most current culture value for that resourcekey?  I thought that when I am using the meta tag in the HTML, the code would take care of it.  Do I have to put something inside the JavaScript as well?

**Comment by RickStrahl** [comment]
No. meta:resourcekey will pick up the active culture. 

You do have to enable culture tracking either in the `globalization` tag in web.config, or using WebUtils.SetCulture() to force the culture to be switched based on browser locale.

**Comment by citybear01** [comment]
How do I use WebUtils.SetCulture?  Do I call this in the code behind?  If so, can you give an example.  If not, then where?

Also, how do I code it in the Web.Config.

Please be kind...this is my first project and need a lot of help here.

**Comment by RickStrahl** [comment]
https://github.com/RickStrahl/Westwind.Globalization/wiki/Auto-Detecting-and-Setting-ASP.NET-Locale-based-on-Browser-Locale
