### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AndyPook** [RickStrahl/Westwind.Globalization#28]
Won't build from a fresh clone.
There seem to be at least 2 missing files
 - ".nugte\nuget.exe"
 - "Westwind.Globalization.Web\app.config"

Am I missing a step?

**Comment by RickStrahl** [comment]
@AndyPook - thanks. app.config shouldn't be there - delete it. nuget.exe is excluded based on default .gitignore for typical Visual Studio solutions. 

Can you check and see if you get the option to 'Enable Package Restore' on the solution and if that will fix it? 

I suppose the simple solution is to add nuget.exe to SCC, but curious why it's exluded. You may still need the 'Enable Package Restore' option either way.

**Comment by RickStrahl** [comment]
Ok - I've updated the latest build. There were a few more missing file references. Code now comes down and should compile and run.

**Comment by AndyPook** [comment]
I've dropped a copy of nuget.exe into .nuget and all is good now. Thanks.

I don't know much about creating nuget packages but nuget.exe is required by nuget.targets which is imported into Samples and Test. According to https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore this is "msbuild integrated package restore" it looks like  you just remove these bits if you want "automatic package restore"

**Comment by RickStrahl** [comment]
Yeah as I mentioned I fixed this in the repro. If you do a pull on latest you'd get nuget.exe down anyway. You'll probably get a conflict now because the versions are likely out of sync.
