### ISSUE TITLE
More intuitive Web AdminLocalization Interface

### ISSUE THREAD

**Issue by amineboussema** [RickStrahl/Westwind.Globalization#29]
regarding the Web AdminLocalization Interface : The Selector of resourceSet on bottom is not so intuitive. I believe making it on the left side and presenting Keys/resourceSets in hierarchical view will be better.

**Comment by RickStrahl** [comment]
Hierachical view is out of question for the moment. Too much overhead in creating these lists - we're already running into issues with single large resource sets. In most cases people end up working in a single resource set most of the time anyway.
