### ISSUE TITLE
Smart Search on Web AdminLocalization

### ISSUE THREAD

**Issue by amineboussema** [RickStrahl/Westwind.Globalization#30]
The search only within the Current resourceSet, I beleive It is something we can improve. because in real world Projects we have to deal with multiple resourceSet, and not have to know each resource within which resourceSet before searching so searching on Whole will be great. And will be more cool if you offer search within content of strings not only the keys.

**Comment by RickStrahl** [comment]
The problem with that is that it's too easy to find too many matches. The idea with searching the keys is that typically the keys are semi unique.

Also, at the moment the filter is applied client side and the client side does not have access to all the detail of all resources - it only holds the key names and the individual resource that is selected. Searching the actual resource detail would require going back to the server and searching through the text for all locales. Doable but would require a completely different approach and affect performance as well - it'd be noticably slower.
