### ISSUE TITLE
Possibility of managing the synchronisation between DbResources on Dev machine and on Production

### ISSUE THREAD

**Issue by amineboussema** [RickStrahl/Westwind.Globalization#31]
In most of real world Apps, we do have Developers team still working on project after launching the web site on production. The situation is : that managers and web masters of Web site can change, edit the resources while in production, and development Team will continue work on their local Dbs, so when deploying the bugs corrections or evolution, with new resources, there are 2 possibilities : 
- Export Whole from Dev MAchine => Prod : Problem erasing what has been done on production DB.
- Manually add (or with scripts) which is a pain 

can we have Export, Import with duplicate control ?

**Comment by RickStrahl** [comment]
Yeah I've run into this myself, but haven't really figured out a way to do this effectively. In essence you need to do merging which is difficult to do. I recently added a timestamp to the localization table which helps slightly in at least determining when something's been changed but that's on a per record basis.

The ideal solution is to use a common data store for localizations that both dev and live apps can see - potentially separate from the main application's database so it's easier to manage. 

I'm open to ideas, but I haven't found a good way to manage data merging unless you explicitly decide that one machine's changes override the other's in case of a conflict.

**Comment by amineboussema** [comment]
Hi thanks,
I believe that xml Export/Import with that TimeStamp field is the way to go. 
When the same key exists in 2 sides : we can ask user for : 
- Override all with Latest 
- Override All with imported
- Let me choose in case by case : that need some more work to present a list of Checkboxes (like the interface with Windows 8.1 when overriding files ... 

Thanks again
Keep the great work!

**Comment by okli23** [comment]
Have you thought about having one master DB, which is used by both devs (to add new resources) and translators, and multiple slave DBs (production, test, alpha, dev etc.), which are synchronized only one-way (with some version control / backup in-between)?
