### ISSUE TITLE
Add the possibility to change the Table Schema Name 

### ISSUE THREAD

**Issue by amineboussema** [RickStrahl/Westwind.Globalization#32]
I didn't found a mean to change the Scema Name for the Table used to store I18N resources. Is it possible ? or planned for next releases ?

**Comment by RickStrahl** [comment]
You can specify the table name in the config file.

**Comment by amineboussema** [comment]
yes I saw it. but can't change the schema from Dbo. to what else

**Comment by RickStrahl** [comment]
I'm not sure what you mean. The tables are created in an existing database. How that DB is schema'd is up to you. And if all fails you can manually create the table.

**Comment by RickStrahl** [comment]
The localization table will go into the default schema only. 

Not planning on adding explicit schema support.
