### ISSUE TITLE
Sort Order on Export Resx Files

### ISSUE THREAD

**Issue by bencurthoys** [RickStrahl/Westwind.Globalization#33]
The way that we've decided to work with this is that the "Master" version of all the resource strings is in the resx file, because we can check that into source control. Normally, in production, we'll be building the strings into the application. Only when we need to activate translations for someone in particular will we use the database localization provider, and we'll sync the database from dev up to the server, let them do their thing, sync the database back down, and then export those strings to resx files and save them in source control. 

One fly in the ointment: at the moment, there doesn't seem to be a defined sort order on exporting strings to resx, it just depends on the order they were added to the database. Which means that different developers generate resx files with strings in different orders, leading to lots of unnecessary changes and conflicts. I don't need to be able to configure what the sort order is - I just need there to be one!

That is, in DbResourceDataManager, at the statement

 string sql = "select ResourceId,Value,LocaleId,ResourceSet,Type,TextFile,BinFile,FileName,Comment,ValueType,Updated from " + Configuration.ResourceTableName +
                             " where ResourceSet " +
                             (!localResources ? "not" : string.Empty) + " like @ResourceSet " +
                             "ORDER BY ResourceSet,LocaleId";

Just add ResourceId on to the end of the ORDER BY clause. 

I would do it myself and issue a pull request, but it's going to take hours to install and remember how to operate Git 'cos I'm just on Subversion at the moment, and changing it to  

                             "ORDER BY ResourceSet,LocaleId, ResourceId"; 
should take all of 2 seconds if you already have a development environment up and running.

**Comment by RickStrahl** [comment]
Good addition. Adding for next release

**Comment by RickStrahl** [comment]
Hmmm... actually looking at my code I already see that sort order on GetAllResources()

```csharp
   string sql = "select ResourceId,Value,LocaleId,ResourceSet,Type,TextFile,BinFile,FileName,Comment,ValueType,Updated from " + Configuration.ResourceTableName +
                             " where ResourceSet " +
                             (!localResources ? "not" : string.Empty) + " like @ResourceSet " +
                             "ORDER BY ResourceSet,LocaleId";
```

Is this the code you're thinking of?

**Comment by RickStrahl** [comment]
Updated - in the ConfigurationManager branch which is my latest code.
