### ISSUE TITLE
Mixed Case Resource Sets

### ISSUE THREAD

**Issue by bencurthoys** [RickStrahl/Westwind.Globalization#34]
I'm not sure how I got into this state, but:

If you manage to get different records for the same resource set with difference cases in the database
e.g. 

    UserControls/LoginInfo.ascx
    usercontrols/LoginInfo.ascx

Then in `GenerateWebResourceResXFiles(bool localResources)` they will come out next to each other from the query in `GetAllResources` because it's ordered by ResourceSet, but as we loop through them, where it detects if the ResourceSet has changed

    // Create a new output file if the resource set or locale changes
    if (ResourceSet != LastSet || LocaleId != LastLocale)

the change of case will make it appear to be a different Resource set because `"UserControls/LoginInfo.ascx" != "usercontrols/LoginInfo.ascx"`

So it will end the file and start a new one - but of course, the file system isn't case sensitive, so the new file will overwrite the old one, which will leave you with a file containing only some of the expected resources. 

MIght possibly fix by changing the line to use String.Compare with Ignore Case

    if (String.Compare(ResourceSet, LastSet, true) != 0 || String.Compare(LocaleId, LastLocale,true) != 0)

thought the best workaround for me in the short term is to update the database to normalise the cases of the Resource Set names.

**Comment by bencurthoys** [comment]
I had to get the source out of GitHub to debug that one, so I can make that change if you like.

**Comment by RickStrahl** [comment]
Sorry, missed this one when it came in. Fixed.
