### ISSUE TITLE
GeneratedResourceHelper

### ISSUE THREAD

**Issue by Yorie** [RickStrahl/Westwind.Globalization#36]
Hello!

If we'll see at GeneratedResourceHelper, we can see lines of code like:
`return DbRes.T(resourceSet, "LocalizationForm");`

First of all, why `resourceSet` passed as first argument of `DbRes.T` which first argument is really resourceId (not *resource set*)?
And also why it uses "LocalizationForm" constant string? So, this code means that i cannot use any resource set name except LocalizationForm?.. It is impossible condition in world of modularity.

May be I misunderstood something, but that makes whole strongly typed resource export classes not usable.
If I wrong, explain, please, how strongly typed code should work then. I've exported database localization resource set into class and got such code:
```C#
public static System.String Hello
		{
			get
			{
				return GeneratedResourceHelper.GetResourceString("TPreinstall","Hello",ResourceManager,GeneratedResourceSettings.ResourceAccessMode);
			}
		}
```

Then in template I've typed:
```Html
@TPreinstall.Hello
```

And result was not what I've been expected:
```Html
TPreinstall
```
It outputs "TPreinstall" (which is really resource set name) instead of "Hello, World!" that is already in database.
If I look at database then, I can find there new row:
```
| ResourceId   |     Value   | LocaleId   |     ResrouceSet  |
| TPreinstall  | TPreinstall |   <null>   | LocalizationForm |
```

Notice: I've manully changed 
```C#
public static ResourceAccessMode ResourceAccessMode = ResourceAccessMode.AspNetResourceProvider;
```
to
```C#
public static ResourceAccessMode ResourceAccessMode = ResourceAccessMode.DbResourceManager;
```
To let strongly typed resources be loaded from database.

**Comment by RickStrahl** [comment]
Looks like this was a refactoring regression that occurred where the values were replaced and parameters moved around. 

Fixed for 2.20
