### ISSUE TITLE
Strongly Typed Resource class properties missing ReadOnly specifier in VB.NET

### ISSUE THREAD

**Issue by thehaunt** [RickStrahl/Westwind.Globalization#38]
I notice that if I generate a Resources.vb file from the LocalizationAdmin interface, that all the properties require me to manually add 'ReadOnly' to the property definition.  Not a big deal with a quick find/replace, but I thought you might like to know.

**Comment by RickStrahl** [comment]
Thanks will take a look. The vb side of things isn't tested very vigorously.

**Comment by RickStrahl** [comment]
Fixed.
