### ISSUE TITLE
Web AdminLocalization - comment not visible

### ISSUE THREAD

**Issue by okli23** [RickStrahl/Westwind.Globalization#42]
It would be great to have a comment relating to the resource visible on the translation page of the Web LocalizationAdmin. Thanks to it translators could know the context of use for the currently translated resource.

I can see that comments are stored in DB and there is even button 'Comment', but disabled by default.
What's the status of this feature, is it work in progress?

**Comment by RickStrahl** [comment]
Fixed in c33aa26407d4ff8b73332a1d3bb52418e59eac71 (development branch currently)
