### ISSUE TITLE
ResourceManager.GetString("SomeResourceId") throws exception

### ISSUE THREAD

**Issue by Avareto** [RickStrahl/Westwind.Globalization#47]
Hi Rick,
After generating a strongly typed class from the LocalizationAdmin interface I tried to call App.Properties.ResourceSetNameClass.ResourceManager.GetString("SomeResourceId") inside my MVC Controller class. But GetString() throwed an exception: "MissingManifestResourceException" (https://msdn.microsoft.com/de-de/library/d17ax2xk(v=vs.110).aspx). But accessing the properties directly like @App.Properties.ResourceSetNameClass.SomeResourceId worked fine. Any idea what went wrong?
Thanks!
Andreas

**Comment by RickStrahl** [comment]
Hmmm... It works for me.

Can you look in the `ResourceTest.cshtml` sample and add:

```html
<h3>.NET ResourceManager</h3>
@Resources.ResourceManager.GetString("HelloWorld")
```

This works for me.

**Comment by RickStrahl** [comment]
FWIW, I've updated the two sample pages to include the `Resources.ResourceManager.GetString("HelloWorld")` section so it's easier to see this work.

**Comment by Avareto** [comment]
I still get an exception when I move the generated strongly typed resource class to a separate assembly. I've attached a minimalistic project (VS 2015->Web->ASP.NET Web Applcation->Single Page Application) to reproduce this issue (remove the .png extension and unzip). Checkout the implementation of WebApplication1.Controllers.MeController.Get().
My current workaround is to use DbRes.T("SomeResourceId") instead.
![westwindglob zip](https://cloud.githubusercontent.com/assets/4642052/11460357/7094b4fa-96eb-11e5-8030-17ffb7a2f28c.PNG)

**Comment by JohnSiluvai** [comment]
Avareto : Is this resolved? I have the same problem when switching resource access mode for typed class to resx.

**Comment by AndreasKuhlmann** [comment]
Probably not...haven't heard anything back.

**Comment by RickStrahl** [comment]
@Avareto ,

I don't quite understand what you are doing. You're linking strongly typed resources from a class library into a Web project? That seems the wrong way to go about this. For this to even begin to work you'd have to have a reference from the class libary to the web project and the reference a type in the Web project to get the correct assembly to load resources from.

I think what you'd want to do is: Export the Resx resources into the class library project (or move them there explicitly). Then export the strongly typed resources into that project and match the namespace to the project structure (ie. `ClassLibrary1.Properties.Resources` although that's optional. Make sure that compiles and check with Reflector that the resources get compiled into the project.

**Comment by RickStrahl** [comment]
So I tried this out with moving resources and this just works fine.

* Move generated resources to ClassLib1.Properties
* Move resources.cs to root
* Change resources.cs like this:
```csharp
 if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new ResourceManager("ClassLibrary1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
```
Note it's pointing at the resources in the ClassLibary1!

Then changed your MeController.Get() method:

```csharp

        [Route("me/get")]
        public string Get()
        {
            // var helloWorld = ClassLibrary1.Properties.Resources.HelloWorld;
            var helloWorld = ClassLibrary1.Properties.Resources.ResourceManager.GetString("HelloWorld") + " from ResourceManager";
            return helloWorld;
        }
```
When I run this I get a Hello cruel World string XML response.
