### ISSUE TITLE
XLIFF and Pseudo-translation support

### ISSUE THREAD

**Issue by JohnSiluvai** [RickStrahl/Westwind.Globalization#48]
1)      Any plans to add features to exporting and importing from db/resx to XLIFF file formats for conversion by industry standard tools?
2)     AddPseudo-translator language generator in the admin tool so that development and unit testing can happen on this test language independent of actual conversion.

**Comment by RickStrahl** [comment]
1) It's not planned. But you can implement it if you like and issue a pull request...

2) Not sure what you mean by this.

**Comment by RickStrahl** [comment]
Closing since no further feedback provided.
