### ISSUE TITLE
Caching issue with globalization library

### ISSUE THREAD

**Issue by maulik31** [RickStrahl/Westwind.Globalization#49]
How can we turn off caching or dynamically clear caching when user changes language data? We need to be able to see data changes instantly but it is requiring us to reboot server after changes are made. Is there a setting within library to turn off caching?

**Comment by AzureRok** [comment]
Maybe this should help:

DbResourceConfiguration.ClearResourceCache();
DbRes.ClearResources();

**Comment by maulik31** [comment]
That worked! Many thanks.

**Comment by RickStrahl** [comment]
What kind of caching are you talking about?

As @AzureRok points out, you can clear resources at the server level when changes are made but that will not affect client or general ASP.NET page caching.

If you have ASP.NET/IIS caching enabled on your pages and the user changes languages, you are going to see old data. Make sure if you're using ASP.NET caching that you inlude **Accept-Language** header as one of the cache differentiators. If you're proxy caching (ie. private or public) pages, then there's nothing you can do to refresh the cache.

None of this has anything to do with with the localization provider - this is all standard caching stuff you have to worry about as part of the application.

**Comment by RickStrahl** [comment]
Closed since there's no further comment on this issue.
