### ISSUE TITLE
IE 11 Issue

### ISSUE THREAD

**Issue by dannykay1710** [RickStrahl/Westwind.Globalization#50]
![image](https://cloud.githubusercontent.com/assets/1044153/11838136/e8e7219c-a3dc-11e5-8da7-6409dd2f5fc6.png)

IE11 doesn't seem to like the resource editor. The listbox down the left is always on two items high and if you do find your items in that list box it also doesn't appear to then save any changes you make.

Tested on Windows 10

**Comment by dannykay1710** [comment]
This also applies to Edge

**Comment by RickStrahl** [comment]
Moved to FlexBox layout for the Localization Admin form and that fixes this issue. Addressed in 69bbb253c9d6bd991a31f8ae2c5feb330889db35.

![image](https://cloud.githubusercontent.com/assets/1374013/12370219/ddc8eb28-bbac-11e5-9064-bd777eb8d4a4.png)
