### ISSUE TITLE
Switching ResourceAccessMode from ASPNet to Resx errors for typed class 

### ISSUE THREAD

**Issue by JohnSiluvai** [RickStrahl/Westwind.Globalization#51]
Example:

<%= Resources.CalculatorHome_Title %> errors when switching ResourceAccessMode from ASPNet to Resx

Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "Westwind.Globalization.Sample.Properties.Resources.resources" was correctly embedded or linked into assembly "" at compile time, or that all the satellite assemblies required are loadable and fully signed.

manager has 0 resource sets in memory.

  public static string GetResourceString(string resourceSet, string resourceId,
                             ResourceManager manager,
                             ResourceAccessMode resourceMode)
        {
            if (resourceMode == ResourceAccessMode.AspNetResourceProvider)
                return GetAspNetResourceProviderValue(resourceSet, resourceId) as string;
            if (resourceMode == ResourceAccessMode.Resx)
                return manager.GetString(resourceId);

            return DbRes.T(resourceId, resourceSet);

**Comment by RickStrahl** [comment]
Did you export your resources?
