### ISSUE TITLE
Cannot delete particular localization for a resource

### ISSUE THREAD

**Issue by mj22552** [RickStrahl/Westwind.Globalization#52]
If I have a resource with multiple localizations and I wish to delete a single localization, that's not possible using the resource editor.

**Comment by RickStrahl** [comment]
Yeah that's true but is that really an issue? Should be pretty rare that you need to do that... 

I suppose we could pop up a dialog that prompts for list with "All Locales" plus each of hte locales available.

Leaving this open but not going to add immediately.
