### ISSUE TITLE
GridView is restricted to number of rows shown?

### ISSUE THREAD

**Issue by balchen** [RickStrahl/Westwind.Globalization#59]
My resource database table has 347 distinct resource keys. In the GridView of the LocalizationAdmin GUI, only 260 resource keys are visible. In the regular view, they are all visible. I couldn't see any obvious reason for this. Is it a bug?

**Comment by RickStrahl** [comment]
Sounds like it, but I'm not sure how to track this. I don't see this with the resource lists I'm using (which are arguably much smaller).

**Comment by balchen** [comment]
Good point. No, I don't have any other resource sets.

But I did have a look at the code for LocalizationService.cs, which wasn't installed with the NuGet package, so I didn't look at that before.

This looks like a smoking gun:

`var sql = @"SELECT TOP 1000
      [ResourceId]
      ,[Value]
      ,[LocaleId]
      ,[ResourceSet]
  FROM [{0}]
 where resourceset=@resourceset
  order by ResourceId, localeId";`

**Comment by balchen** [comment]
I have four languages in my resource set (invariant, Norwegian, Danish, and English). There are some missing entries for Danish, so 4 * 260 - missing entries = 1000.

**Comment by RickStrahl** [comment]
Makes sense. I can't recall offhand why I even filter on TOP 1000 but that should probably go away. I'll review with the intent to remove the TOP 1000.

**Comment by balchen** [comment]
Thanks, Rick.

**Comment by RickStrahl** [comment]
Looks like that code shouldn't have been there in that form anyway. Instead the code should be using a modified version of  `Manager.GetAllResources` which should get all resources regardless of size. Note that if your list is very long this can be potentially be slow, but at least they'll all show up.

**Comment by RickStrahl** [comment]
Fixed with 1c55652b3941a98bf10357aec9c81c9d8c732df1

**Comment by ornolisvt** [comment]
Thanks. I modified the source code and paginated the results
