### ISSUE TITLE
Sample ResourceTest.aspx JS error

### ISSUE THREAD

**Issue by pazams** [RickStrahl/Westwind.Globalization#60]
Error from Chrome v48:
![localization-error](https://cloud.githubusercontent.com/assets/9962080/13915029/dc484e38-ef5a-11e5-8093-50883a8453d6.png)

Seems this error is due to nested forms.
from https://www.w3.org/TR/html5/forms.html#the-form-element :

> Flow content, but with no form element descendants.

**Comment by RickStrahl** [comment]
This was previously fixed. Thank you.
