### ISSUE TITLE
Saving a ressource after double-click

### ISSUE THREAD

**Issue by marcus-michaels** [RickStrahl/Westwind.Globalization#65]
Hi,

I do have a question regarding saving from the integrated editor in version 2.2.1.
I do use invariant and German ressources.
When I doubleclick a ressource and edit it and then click SAVE the ressource sometimes ends up in the wrong textarea and the wrong savebox changes its color to green, meaning a German ressource is edited, but upon closing the invariant ressource is overwritten instead.

Any hints?

**Comment by RickStrahl** [comment]
Not sure. Can you give your exact repro steps please?

**Comment by marcus-michaels** [comment]
I do open the localization admin form with the proper ressource selected. There are always two entries (one invariant, one German).
If I then double click the German ressource, the editor opens. I make my changes, click save and the ressource ends up in the textarea, the checkbox turns green and click save again.
Sometimes tho, I want to edit the other entry too and it opens properly in the editor, but when clicking save then, it ends up overwriting the German textarea and not invariant or vice versa.
If I however close the form after each edit it works fine. It only happens when editing two languages and not closing the form inbetween.

I hope it is understandable?

**Comment by RickStrahl** [comment]
Yeah this is a binding issue. There's an active item that is directly bound to one of the resource entries. If you open multiple windows the last one is the only one that really has any effect and is applied.

In short you can only edit one thing at a time. I need to look into that and see if there's a better way to deal with this but this mostly done to keep the databinding relatively simple. Doing it any other way we'd have to unbind all entries on every save operation.

**Comment by RickStrahl** [comment]
This was addressed a bit back when the resource update logic was changed and updated to trigger on losing focus.
