### ISSUE TITLE
Default resourceset for DbRes.T

### ISSUE THREAD

**Issue by craigvn** [RickStrahl/Westwind.Globalization#68]
If I use this code then all is fine
@DbRes.T("Forms.FormEdit.MobilePhone", "Resources")

If I write this however it doesn't find the reource
@DbRes.T("Forms.FormEdit.MobilePhone")

Is there a way to default the resourceset?

Thanks

**Comment by RickStrahl** [comment]
Hmmm... the default resourceSet is `Resources` so those two should be the same.

**Comment by juanalo** [comment]
I´m using this great library storing reosurces in a Database. When I call the function without specifing ResourceSet and if I have AddMissingResources=True, it creates a new entry with empty resource set and thats why getting the resource it can´t find.

**Comment by RickStrahl** [comment]
Yes "" is a valid ResourceSet and reviewing the code I see that the default if not passed is `""` which means you get the blank resource set rather than "Resources".

https://github.com/RickStrahl/Westwind.Globalization/blob/master/Westwind.Globalization/DbResourceManager/DbRes.cs#L98
