### ISSUE TITLE
Using grid don´t update correct locale

### ISSUE THREAD

**Issue by juanalo** [RickStrahl/Westwind.Globalization#69]
I´m using the Translation page to edit resources.

Using grid with different locales don´t work well. I have thre locales: Invariant, es, fr.

When editi fr resource values it affect both locales: spanish and french. After that I close the grid and reload resources and I can see that it´s not working.

If I edit es resource locale and navigate to the next text area with the mouse clicking, it´s updating ok. If I navigate to the next es resource locale with tab key, passing throught fr resource locale, it gets the fr locale and updates to es locale.

Summary, the problem with the gird it´s when I´m update fr resource locales it´s update es locale instead fr.

I have to use the standard translation instead the quickly grid.

**Comment by RickStrahl** [comment]
Hmmm... yes I see it as well. Looks like the issue is that it's updating based on position, not based on the actual language code.

**Comment by taufik-alto** [comment]
Hi

I think there is issue in the **GetAllResourcesForResourceGrid** function for **localizationService.ashx**.

var totalLocales = itemList.GroupBy(it => it.LocaleId).Select(it=> it.Key).ToList();

Above is the code having issue - it does not sort the totalLocales ; but the items are sorting accordingly.

May need changed it to 

var totalLocales = itemList.GroupBy(it => it.LocaleId).Select(it=> it.Key).**OrderBy(x=>x)**.ToList();

Regards
