### ISSUE TITLE
Resource Overrides

### ISSUE THREAD

**Issue by ralph1996** [RickStrahl/Westwind.Globalization#70]
I am finding a need to allow for overrides in the resource definitions.  Basically we have multiple installations of our code and in each installation we may need to change the resource strings.  However we want to be able to update the existing code with new code and resources without disturbing the resources in that particular installation.

My thought was to create a second resource table in the database for overrides and in places where the library loads resources from the database it uses a construct like isnull(overrideTable.value, resourceTable.value).  

Of course we would need to also modify the LocalizationAdmin and/or write a new interface to get the values into the override table but that can be done.  I just wanted to check with you in case something like this has already been done or if you have any suggestions or concerns to this approach.

Thanks!

**Comment by felixcollins** [comment]
You can create a custom culture for your overrides e.g "en-US-cust". Beware: for this to work you must be able to Register the CultureInfo with the system (tricky with Azure web app). You can then simply set the thread UI culture to your custom one. Any missing resources will nicely fall back. All of Rick's excellent tools for creating and updating will still work with this solution. Google for details of creating and registering custom cultures on windows.

**Comment by ralph1996** [comment]
Thanks for the reply.  However this does not solve my issue.  I want to be able to have a parallel database table that contains overrides for all languages in the base localization table.  The point is to have a standard set of translations that we distribute with the application but allow the client the ability to override those translations without actually touching the base translations.  This is because when we publish new versions of the application we want to be able to overwrite the base set of translations to make sure any new or changed data is deployed - but we don;t want to upset the client data if they made changes.  It is kind of like a Child Theme in WordPress.

I have more or less resolved the issue by creating a view in the database that handles the merging of data from the two tables.  Then I point the applications ResourceTableName to this view.  We then create a separate application that contains the LocalizationAdmin only (Called it ResourceManager) and we can point the ResourceTableName to either the base localization table or the override table depending on who is the consumer.  This allows us to edit the base localizations ourselves but also give clients (or more likely our administrator running in the client environment) the ability to edit the overrides, while the application accesses the view that aggregates the two tables properly.

Hopefully this will help others that might have the same issues with a solution that does not require modifying the globalization code.

Thanks for a great tool.

**Comment by RickStrahl** [comment]
@ralph1996 Wouldn't the custom locale if stored in the DB address that same scenario as @felixcollins mentiones?  Assuming the locale is set up (or you don't even have to set up one - choose an existing obscure locale and customize the CultureInfoSettings to match your needs) you could store the customizations in that locale format which would give you the side by side behavior you are looking for, no? No separate table, but separate indexed entries.

**Comment by ralph1996** [comment]
The problem with that, if I understand you correctly,  is that if the resource is not defined in the custom locale then the resource will revert to the invariant locale.  This is not what is wanted.  We need to be able to have an override for the Invariant language but also overrides for the same resource for all other languages we will support.

So Resource STRING1 has a definition in en (invariant) as well as de and es.  We want to be able to override all three of those languages independently. The override for en would not be the same as the override for de.  

The problem is that even if we created three separate custom locales, if the resource definition does not exist in the custom locale (example custom-de) it will default to invariant (en) as opposed to the paired locale for the custom locale (which would be de).

Note the overrides may be a sparse population of the base resources and also may include resources not in the base resources.  These are all combined in the view to create one merged set of resources including all the unique resource identifiers in both tables and giving priority to the values in the records in the override table.

Finally, another benefit of doing it the way we are doing it is that we can allow clients (or our less technical administrator) to edit their own overrides using the LocalizationAdmin as is without worry that they will destroy the base resources since they will only have access to the overrides table. And we can do this without having to make changes to the existing library or Admin code.  

Hope that clarifies what I am trying to do.  I appreciate your thoughts.

**Comment by intranel** [comment]
It sounds as though you are trying to do much the same thing we are doing. I'm not sure your understanding of the culture fallback system is correct though (either that or I have a misunderstanding which needs correcting). I've tested it using Westwind.Globalization and it worked for us.  Some examples of fall back chains... (note that the column width for the LocaleId in the localization table may need to be increased to fit the allowable length)

en-NZ-custom (falls back to) en-NZ (then to) en (then to Invariant)
es-ES-custom (falls back to) es-ES (then to) es (then to Invariant)
de-custom (falls back to) de (then to Invariant)

Is that not what you need?

**Comment by intranel** [comment]
BTW: "en" is NOT the Invariant culture. "" (empty string) is.

**Comment by ralph1996** [comment]
You have hit the core.  You are correct, I was not fully understanding the fallback process.  I was thinking only in terms of the base locales.  You are correct your approach would work.  And I incorrectly stated en was invariant - I realize "" is invariant - just thinking too US centric when writing this.

The only reason then to use our approach is because we want to prohibit some set of users from possibly modifying the base localizations as well as it will be easier for us to overwrite the base localizations when we publish new code/data since we can just replace the entire table as opposed to filtering based on the LocaleId. 

We could of course do all this by modifying the LocalizationAdmin to prohibit users from entering data for the base Locales but that is what we are trying to avoid at the moment. The solution we have allows us to get the result we want without any changes to the library or admin.  This also allows us to be able to update to newer versions of the library etc in the future without worrying about merging any changes etc.

Thanks for you help on this and for educating me on the functionality of the library.  I have not had to implement localized resources in applications since the 1990s so I am a bit rusty and the tools have changed quite a bit.

**Comment by intranel** [comment]
Rick, is it possible to split the Localization table by LocalId? If so that might be a solution for ralph1996. If not then it would probably not be hard to modify Westwind.Globalization to suck up multiple tables.

However... I would advise you to put all your localizations (note US spelling for you benefit!) in the one table. If you have multiple tables you have to modify your DB schema every time you add or remove a culture translation (custom or otherwise). This is not a good idea. 

If the Localization Admin does not have a feature to restrict to certain languages based on permissions already (I do not know the code well) I'm sure it would be a feature that would be ripe for merging if it was implemented well.

**Comment by ralph1996** [comment]
I don't understand why we would have to change the database schema when adding or removing a culture translation.  We simply have a second table with the exact same schema as the base localization table.  

An override for a resource in the override table has the same localeIds and ResourceId as in the base table.  The database view just ends up pulling the value from the override table instead of the base table if it exists.  The override table can be empty for all that it matters.  Then you can individually add the resources you want to override by adding the same ResourceId and LocaleId to match the base record you are overriding.  You can do this with as many languages as you want - no need to modify the schema.

To be honest we are also using this for customizing UI strings for clients that may or may not be interested in localized versions.  It allows us to use the overrides to do things like change the word "Customer" to "Client" in all strings that use the word "Customer". We can simply do a database query to copy the records with "Customer" in them to the override table and change "Customer" to "Client".  This then allows us to update the base table by replacing all the records without trashing the "Customer" to "Client" mapping.  of course if we add a record to the base table that has "Customer" in it we will need to copy that into the override table as well - but we won't overwrite the overrides and the client will get all new resources that have been added.

**Comment by intranel** [comment]
Sorry I thought you were putting a new table in per custom translation. My mistake.

I still don't understand why you can't do all that in one table. We have the same requirement from out client - a multi-tenanted system where some tenants wish to change certain words in the app to fit what is used internally.  

Each tenant has a custom culture defined (say "en-US-ralph"). In the invariant culture "" we put an entry in for say, "CUSTOMER_LABEL"  of "Customer". If ralph wishes to change the string for CUSTOMER_LABEL from "Customer" to "Client" then we put an entry in the Localization table with LocalId set to "en-US-ralph". Now when we look up the string for CUSTOMER_LABEL using the custom culture of "en-US-ralph" we get "Client". One could do this for every string lookup or by setting the CurrentUICulture. If you look up another resource for which the override with "en-US-raplh" does not exist it will fallback progressively to en-US, then en and finally to "" (Invariant) until a resource is found (or not).

**Comment by ralph1996** [comment]
I completely agree it can be done that way.  From our standpoint though we prefer to keep the overrides completely separate so that we can simply point an instance of the LocalizationAdmin to the override table and they can have at it without the possibility of changing the base translations.

This is strictly a maintenance preference on our part at this point.  Your approach is perfectly fine. It all  depends on how you want to do the resource management and what restrictions you have regarding the individuals who will manage the data.

**Comment by intranel** [comment]
Yep, agreed. You either need to modify the loading of the resources by creating a view to load from (or modifying WestwindGlobalization) OR you could modify the LocalizationAdmin to do what you need.

**Comment by RickStrahl** [comment]
Some interesting points are raised in this discussion, but I don't think I'll be implementing any of these special edge cases. As @intranel points out you can get things to work using what is built in and what ASP.NET/.NET localization provides. It's not always pretty but it works, and frankly the suggested workarounds like splitting up tables is even less pretty :-) and would be confusing to deal with generically and to configure.
