### ISSUE TITLE
AddMissingResources, sql fails to add row

### ISSUE THREAD

**Issue by fruitbatinshades** [RickStrahl/Westwind.Globalization#74]
I'm using the latest version but the AddMissingResources sql that is generated fails on SQL Server 2014 with :

`Must declare the scalar variable "@ResourceID".`

Any idea how to fix this?

`exec sp_executesql N'insert into Localizations (ResourceId,Value,LocaleId,Type,Resourceset,BinFile,TextFile,Filename,Comment,ValueType,Updated) Values (@ResourceID,@Value,@LocaleId,@Type,@ResourceSet,@BinFile,@TextFile,@FileName,@Comment,@ValueType,@Updated)',N'@ResourceId nvarchar(9),@Value nvarchar(9),@LocaleId nvarchar(4000),@Type nvarchar(4000),@ResourceSet nvarchar(9),@BinFile varbinary(8000),@TextFile nvarchar(4000),@FileName nvarchar(4000),@Comment nvarchar(4000),@ValueType int,@Updated datetime',@ResourceId=N'Warehouse',@Value=N'Warehouse',@LocaleId=N'',@Type=N'',@ResourceSet=N'Resources',@BinFile=NULL,@TextFile=NULL,@FileName=N'',@Comment=NULL,@ValueType=0,@Updated='2016-07-26 09:07:52.483'`

**Comment by fruitbatinshades** [comment]
Its a case sensitivity issue even though I have a _CI collation.

**Comment by RickStrahl** [comment]
I think this was fixed a while ago by normalizing parameters in Sql statements. if this is still an issue please re-open.
