### ISSUE TITLE
The grid don't load more than 1000 item

### ISSUE THREAD

**Issue by ornolisvt** [RickStrahl/Westwind.Globalization#75]
I'm using the grid to translate a resources set, but the grid could not charge more than 1000 objects. My resource set have more than 1000. There is no way to paginate the grid ?

**Comment by balchen** [comment]
Sounds a like duplicate of #59 . Maybe you should update your copy of WestWind.Globalization.

**Comment by RickStrahl** [comment]
FWIW, this change hasn't been merged in yet, but I'll take a look as soon as I get a little more time. I'll leave this issue open until that happens.
