### ISSUE TITLE
Security for Localizationadmin page

### ISSUE THREAD

**Issue by sheryever** [RickStrahl/Westwind.Globalization#78]
How to add security to Localizationadmin/index.html in mvc.

the page is accessible to everyone.

**Comment by bsoulier** [comment]
You can use [web.config per location configuration](http://weblogs.asp.net/gurusarkar/setting-authorization-rules-for-a-particular-page-or-folder-in-web-config) to manage specific rules:

`<location path="Localizationadmin">`
`    <system.web>`
`         <authorization>`
`           <allow roles="Admin"/>`
`            <deny users="*" />`
`          </authorization>`
`      </system.web>`
 ` </location>`

**Comment by sheryever** [comment]
Thanks
