### ISSUE TITLE
Cant get SQL CE to create tables 

### ISSUE THREAD

**Issue by saqibshakil** [RickStrahl/Westwind.Globalization#79]
I get an error "LocalizationTableNotCreated\r\nInvalid set option. [ Set option = ANSI_NULLS ]"

**Comment by saqibshakil** [comment]
Didnt read the document well enough

**Comment by RickStrahl** [comment]
What was the issue?

**Comment by saqibshakil** [comment]
I didn't initialize the right manager in the global.asax maybe a separate
doc on how to setup different db types would help
