### ISSUE TITLE
Looking for a Alternate Method to DbRes.T() which ignores case when it calls the ResourceId. 

### ISSUE THREAD

**Issue by padam10** [RickStrahl/Westwind.Globalization#81]
In c# , I am calling as   DbRes.T(“helloWorld”).  
In the sql db : ResourceId is stored as  : “HelloWorld” and Value is stroed as  “Hello World” 
It returns  “helloWorld” because it cannot find a resouceId with the exact match. I was hoping for an alternate method which ignores case and returns the value

**Comment by RickStrahl** [comment]
There are a number of reasons for this. First that's the way the localization works in .NET - it's case sensitive, so this is following the base convention, but it's also more expensive to to do lookups based on case.

**Comment by padam10** [comment]
Rick, thank you for the clarification.  I actually used the IgnoreCase and it seems to be working : 
 DbRes.GetResourceManager(resourceSource).IgnoreCase = true;
DbRes.T(“helloWorld”).
It is returning "Hello World" but I am not sure if it is recommended to use like this.

**Comment by RickStrahl** [comment]
You also need to make sure that the DB is set up to support date sensitive lookups using an appropriate character set.

Ultimately you should make sure your keys are properly cased because if you ever switch back to Resx by exporting your case insensitive keys will fail.
