### ISSUE TITLE
Fix for bing translations

### ISSUE THREAD

**Issue by Snipsnoop** [RickStrahl/Westwind.Globalization#82]
Hey

The bing transation kept bugging out for me, however after a few small changes I was able to get it working again. This is a quickfix and will use the new API to issue tokens.

Set BingClientId (web.config) to one of your keys from the Cognitive Service in azure.
http://docs.microsofttranslator.com/text-translate.html#!/default/get_Translate

In Westwing.Globalization \ Utilities \ TranslationService.cs 

Make the following two changes

Change GetBingAuthToken & TranslateBing

`

        public string TranslateBing(string text, string fromCulture, string toCulture,
            string accessToken = null)
        {
            string serviceUrl = "http://api.microsofttranslator.com/v2/Http.svc/Translate";

            if (accessToken == null)
            {
                accessToken = GetBingAuthToken();
                if (accessToken == null)
                    return null;
            }

            string res;

            try
            {
                var web = new WebClient();
                var appid = "Bearer " + accessToken;
                string ct = "text/plain";
                string postData = $"?appid={StringUtils.UrlEncode(appid)}&text={StringUtils.UrlEncode(text)}&from={fromCulture}&to={toCulture}&contentType={StringUtils.UrlEncode(ct)}";

                web.Encoding = Encoding.UTF8;
                res = web.DownloadString(serviceUrl + postData);
            }
            catch (Exception e)
            {
                ErrorMessage = e.GetBaseException().Message;
                return null;
            }

            // result is a single XML Element fragment
            var doc = new XmlDocument();
            doc.LoadXml(res);
            return doc.DocumentElement.InnerText;
        }

        public string GetBingAuthToken(string clientId = null, string clientSecret = null)
        {

            string authBaseUrl = "https://api.cognitive.microsoft.com/sts/v1.0/issueToken";

            if (string.IsNullOrEmpty(clientId))
                clientId = DbResourceConfiguration.Current.BingClientId;

            if (string.IsNullOrEmpty(clientId))
            {
                ErrorMessage = "Subscription key must be provided";
                return null;
            }
            // POST Auth data to the oauth API
            string res;
            try
            {
                var web = new WebClient();
                web.Encoding = Encoding.UTF8;
                web.Headers.Add("Ocp-Apim-Subscription-Key", clientId);
                res = web.UploadString(authBaseUrl,"");
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.GetBaseException().Message;
                return null;
            }
            return res;
        }

`

Token should really be cached for 8-9 min (expires after 10), this would speed up the translations

**Comment by RickStrahl** [comment]
This no longer works either :-( Microsoft keeps changing their bloody API endpoints.
