### ISSUE TITLE
IE Edge Translate bug

### ISSUE THREAD

**Issue by kourosko** [RickStrahl/Westwind.Globalization#83]
When you are on Edge and you use the translator when you click button use this to save the resource then it doesn't save anything.

fix: in listController.js file
 // call back from translate controller
        $scope.$root.$on("translateComplete", function (e, lang, value) {
          ....

                      // assign the value directly to field
            // to force to $dirty state and show green check
          $timeout(function (tmp) {
                var $el = angular.element('#value_' + index);
                $el.val(value)
                    .controller('ngModel')
                    .$setViewValue(value);
                     $el.focus();
                   //old code
                 //  vm.onSaveResourceClick();

                 //new fix
                     //I added a second timeout so IE can focus the right input
                          $timeout(function () {
                                    vm.onSaveResourceClick();
                            });
            }, 100);
        });`

**Comment by RickStrahl** [comment]
Sorry for the long delay here. Fixed in latest build. Thank you for the fix - would have never caught that with IE. FWIW, it's IE that has the problem not Edge.
