### ISSUE TITLE
Use exported resource files as the source of data.

### ISSUE THREAD

**Issue by meywd** [RickStrahl/Westwind.Globalization#84]
First thanks for a great library, really appreciate the efforts.

We have the normal dev, staging, and production environments and we use the editor and the database as the store, however we also export the resources to files, mainly as a backup/source control, but we want to also use them in the production environment as the default source instead of the database, from what I read in the documentation this is possible, however I am not finding the way to do it, which configuration keys to use.

**Comment by RickStrahl** [comment]
You can do it through the Admin UI. Use the Export to Resources option. You need to configure the location and namespace for the generated resources and strongly typed resources classes.

**Comment by meywd** [comment]
we have them configured, and the files show in project, however where in the configuration or in code do we choose where to look first(db vs files)

**Comment by RickStrahl** [comment]
There is no support for where to look 'first' it's one or the other. You can set this up when you configure the provider or in the configuration.

```cs
opt.ResourceAccessMode = ResourceAccessMode.DbResourceManager;  // .Resx
```
