### ISSUE TITLE
Question: Supporting lower level of .net framework

### ISSUE THREAD

**Issue by ademgashi** [RickStrahl/Westwind.Globalization#86]
Hi, @RickStrahl I hope this message finds you well with everything, health, family, finances and all other things that matter to you most. Firstly kudos and thank you very much for this incredible wonderful package. I looked at the youtube video and I loved it, and secondly is there a way to make this work with web apps that are build on .net 3.5? Maybe just recompiling it on .net 3.5 will work??? are there any strict dependencies on .net 4.5 as said in description...

Please whenever you can let me know...

Best Regards
AG.

**Comment by RickStrahl** [comment]
We don't support .NET 3.5 for this project any longer. There are dependencies on other libraries that require .NET 4.5 so this is the base line.

It's possible that with some effort you can make it work on .NET 3.5, but you're on your own with that.
