### ISSUE TITLE
Signed Assemblies

### ISSUE THREAD

**Issue by marshall1234** [RickStrahl/Westwind.Globalization#88]
Any chance of getting signed assemblies? We are looking at using this library in a project which is using signed assemblies. From what I can see it would mean that the Globalization and Utilities would need to be signed.Thanks.

**Comment by RickStrahl** [comment]
We're not going to ship signed assemblies, so if you need that you'll have to build from source and sign yourself. This may change in the future when NuGet gets better support for signed/unsigned assemblies in the (not too distant) future

**Comment by melucas** [comment]
Hi @RickStrahl,

I'm trying to sign the WestWind DLLs (Westwind.Globalization.dll, Westwind.Globalization.Web.dll, Westwind.Utilities.dll, Westwind.Web.dll) using the ilasm.exe and ildasm.exe trick. 

However, when we try to access a translation using DbRes.T() or  GetGlobalResourceObject() in the code the HTML or code of a WebForms application, it complains that the Westwind.Utilities or one of it's dependencies is not signed.

Any idea what that might be?

Thank you,
Michael

**Comment by melucas** [comment]
The Globalization works until you add a using for Westwind.Globalization to access DbRes.T() in the code behind on a WebForms page.  That is when the "a strongly-named assembly is required" error happens for 'Westwind.Globalization'.  If I sign all 4 of the DLLs, the error happens on 'Westwind.Utilities'.
