### ISSUE TITLE
Move web resource editor to a separate nuget package

### ISSUE THREAD

**Issue by zivkan** [RickStrahl/Westwind.Globalization#9]
Hello,

Can you move the web resource editor to a separate nuget package to WestWind.Globalization, please? Or provide it as a separate git repository that people can clone. I was quite surprised when I added the nuget package to a .dll assembly, and it added some javascript and aspx files.

We have a big solution, and several assemblies use DbResourceDataManager (currently we have a copy of this repo, which we added as a project reference, but I want to use the nuget package instead). Most of these assemblies are not web projects, and it will take a lot of time to delete these files from all the projects that the nuget package would add. We don't use the resource editor on our web application either. We have it on a separate, internal-only website, so I would need to delete these files from our web projects too. 

PS, I'm happy to see you extracted interfaces on some of the classes recently. Currently I can't unit test anything that uses DbResourceDataManager, unless I create my own wrapper. But, it would be a lot of work to change all references to the new wrapper class. Although, if I did, then I would only need to delete the web files added by the nuget package once, so maybe it's a good idea for now.

**Comment by RickStrahl** [comment]
I have to take a look and see what can be pulled out and what has to stay. The Localization Admin stuff is all stored in single folder so it's not exactly hard to delete that, but I get what you're saying in class lib projects. I've run into this myself.

As it is we're going to end up with a bunch of packages for Westwind.Globalization in 2.0 because each of the data provider implementations has to live in separate assemblies/packages because of the SQL provider dependencies. Not looking forward to maintaining all these nuget packages for a single library.

**Comment by zivkan** [comment]
Most of the localisation admin is in a single folder, but the nuget package also adds 2 scripts into the  scripts folder (again, easy to delete for assemblies, but requires more effort to delete from a web app that already had a scripts folder), plus 2 more files in the project root. Additionally, when I upgrade from an older version of the nuget package to the current version, the files get added again. So, control-click 4 files/folder, then delete needs to be repeated for every project that uses the package. I haven't checked our version of the localisation admin page, but if we've made customisations, I'm a bit concerned we'd have to reapply them. Source control helps, but it's still extra work in upgrading.

I don't have any experience building nuget packages, but can it all be automated with a build script? Using a combination of a build server and some powershell scripts, we build our solution from source control, run some executables (DB migration scripts, modify config files), deploy some executables on one server, deploy different executables on a different server, stop/start windows services, etc. I hope that building a few nuget packages is a lot easier than this.

I think it should be a one time investment to write a build script. Afterwards, I guess it wouldn't be any more effort to maintain several nuget packages (that have the same release cycle, at least), compared to the effort of one package.

**Comment by rintje** [comment]
+1 for this issue, although i understand the practical concerns of having multiple packages to maintain.

We don't use the editor at all, because we introduce resource updates in the resource database in another way (scripting). On each update of the globalization nuget package, we need to get rid of the editor stuff introduced in our project.

**Comment by RickStrahl** [comment]
The latest beta has this implemented. There are now several NuGet packages for Westwind.Globalization and these packages are live with the Pre-release flag on NuGet:

* Westwind.Globalization - ResourceManager, DbRes, and various tool support classes
* Westwind.Globalization.Web - ResourceProviders, JavaScript Resource Handler, Admin Interface, * WebForms controls etc. 
* Westwind.Globalization.MySql - My Sql data implementation
* Westwind.Globalization.SqLite - not live yet
* Westwind.Globalization.SqlServerCe - not live yet

**Comment by RickStrahl** [comment]
Just as a follow up the latest beta releases now have separated NuGet packages for:

* Westwind.Globalization
* Westwind.Globalization.Web
* Westwind.Globalization.MySql

Other providers data will be added when V1.0 gets released.

**Comment by rintje** [comment]
Thanx!
