### ISSUE TITLE
Winforms

### ISSUE THREAD

**Issue by oghenez** [RickStrahl/Westwind.Globalization#90]
Can this be used with a WinForms project or just asp?
Can i put my resources in a database

**Comment by RickStrahl** [comment]
Yes you can use it with WinForms (or anything else really), but I would not recommend it as a runtime solution. The better approach is to use the tool for resource editing and then export to Resx.

I wrote a blog post about this some time ago here:

https://weblog.west-wind.com/posts/2016/May/18/Using-WestwindGlobalization-to-edit-loose-RESX-Files
