### ISSUE TITLE
.Net MVC - multiple SQL server tables for Localization

### ISSUE THREAD

**Issue by KumarSunit** [RickStrahl/Westwind.Globalization#91]
Hi
Can you please let me know how to use multiple sql tables to get localization.
Currently, configuration showing for single table

```
<DbResourceConfiguration>
    <add key="ConnectionString" value="**SQL Connection String**" />
    <add key="ResourceTableName" value="Localizations" />
```

I want to use one more table e.g. LocalizationsSecond (another table)

Thanks

**Comment by RickStrahl** [comment]
This is not supported at the moment. You'll be able to do this in 3.0 with some trickery. In 3.0 you can do this but you have to use the dbProvider specific implementations not the stock ASP.NET/.NET features. 

The real question is why use multiple sources - this is going to be a huge maintenance issue as you're trying to figure out what goes with what. And resource administration definitely won't be able to work with multiple tables simultaneously.

In 3.0 you can create specific DbResInstance() instances that take separate configuration objects as input. There you can change the table (and anything else about configuration), but at that point you have to use that instance.
