### ISSUE TITLE
WestWind table customization

### ISSUE THREAD

**Issue by Gioking** [RickStrahl/Westwind.Globalization#92]
Hi Rick, regarding westwind globalization I use already the framework and it is really stable and usefull.
Now I have to solve a problem with my customer so I ask you: it is possible
have more than one localization table ? and chose the right table at runtime ?
In the mvc 5 ControllerBase in the method: OnActionExecuting I did try to instanciate the class: DbResourceConfiguration using the method:ResourceTableName to specify another table eg. "NewLocalTable" 
but nothing appen I mean once I open the administration page I don't see CreateTable icon up right in the page.

Also can I add a custom field in the table ?

Thank for you help

**Comment by RickStrahl** [comment]
You can set `DbResourceConfiguration.Current.ResourceTablename` during startup. But this value is static so you can't change it or it will affect all requests so changing that value during requests is not a good idea.

V3 adds dbResInstance() which can have its own configuration information associated with it. So if you explicitly declare `DbRes` in your page/controller/view and then you can dynamically assign a custom configuration and set the `ResourceTablename` property for just that instance.

**Comment by Gioking** [comment]
Thanks you Rick I solved as you suggestions.
