### ISSUE TITLE
Handling resources not loading due to network failures

### ISSUE THREAD

**Issue by shaneholder** [RickStrahl/Westwind.Globalization#96]
Hi,

I'm trying to determine how to handle a situation where the resources are not loaded from the database due to a network or database failure.  

The situation that occurs is that the keys for the resources are returned to the client and the system seems to cache an empty list of resources.  So what I think I want to do is determine that localizations have not been loaded clear the Globalization caches and log the error that prevented the localizations from loading.

From previous issues I gleaned that the following should clear the resource caches.
```
DbResourceConfiguration.ClearResourceCache();
DbRes.ClearResources();
```
Is this still the preferred way of clearing the caches?  And is there a way to get access to the DbResourceDataManager.ErrorMessage property so that I can log the issue?

Also, should Globalization detect the failure and attempt to reload the resourceSet internally on it's own?

**Comment by RickStrahl** [comment]
That's one of the dangers of running with resources from a database - if the DB is not there - no resources.

Frankly I would not recommend running production sites with resources from a database. I recommend you do dev with the Db provider so you can edit and manage resources, then for production export to Resx and run with that.

The big problem with all of this is that the Resource manager system in .NET is horribly convoluted and nested. Any load error eventually trickles down into a ResourceReader() which has no connection to the ResourceManager or anything higher up in the chain. So there's no way to get error information out of the system and all the way back up - especially not with the static `DbRes` object.

In the next update there will be an instance version of `DbRes` (in prep for .NET Core) and that does have at least the state to store error info, but I haven't thought about how to get the error info into that object either at this time.

**Comment by shaneholder** [comment]
You've made it too darned convenient to run from the DB in prod, this is
especially convenient when working with translators. :)  I worked around
the issue by resolving a translation somewhere in the request path for a
well known key and ensuring the value was not equal to the Key.  If the
values were equal I clear the Localization cache and try again in 1 s, if
that fails then I show a 404 or something that forces the user to do an
F5.  My concern was that transient DB failures lead to the display of
incorrect data and the solution to this is not obvious.  I think surfacing
the error someplace would be nice, but as I recall the real problem is that
there was no distinction between resources being returned that just did not
exist in the database, or an error from the database.  I don't have access
to the code right now but I think a dictionary was being returned
regardless of retrieval to the DB or not.


Shane

**Comment by RickStrahl** [comment]
Hi Shane

Sure, but the risk remains that if resources are not available you get only the resource key values. At least the DbRes tooling gives you the resource key value if the DB is not responding or keys are otherwise missing so at least you don't get an empty UI as is the case with bad keys in the native ResourceProvider/Managers.

I don't have a good answer for you beyond what you're already doing other than if you want reliable resources, export to Resx and bind those to your application. That will guarantee reliable results. Then use the DB only when you actually need to modify resources.
