### ISSUE TITLE
MySQL provider connectionString via code not working

### ISSUE THREAD

**Issue by tomerpeled** [RickStrahl/Westwind.Globalization#97]
Hi,

I succeed to work with the MySQL provider while defining it via the web.config like this:
```
  <connectionStrings>
      <add name="Localization" connectionString="server=myserver;uid=myuser;pwd=mypassword;database=Localizations" providerName="MySql.Data.MySqlClient" />
  </connectionStrings>
```

But when trying to override it via code it doesn't work:
```
DbResourceConfiguration.Current.ConnectionString = "server=myserver;uid=myuser;pwd=mypassword;database=Localizations"; 
            DbResourceConfiguration.Current.DbResourceDataManagerType = typeof(DbResourceMySqlDataManager);
```

Notice that when working with:
`DbResourceConfiguration.Current.ConnectionString = "Localization";`
Instead of overriding the **connectionString** it works...

The SQL server provider is working in both scenarios (Config + override in code).

Anything I'm missing?

**Comment by liviudragnoiu** [comment]
ResourceSetLoadingFailed:Unable to cast object of type 'MySql.Data.MySqlClient.MySqlConnection' to type 'System.Data.SqlClient.SqlConnection'.

also from config doesn't work for me

**Comment by RickStrahl** [comment]
Please show your code...

**Comment by liviudragnoiu** [comment]
i have 
` <add name="mySqlConnection" connectionString="server=server;port=3306;user id=user;password=pwd;database=localizations" providerName="MySql.Data.MySqlClient" />

<entityFramework>
    <defaultConnectionFactory type="MySql.Data.Entity.MySqlConnectionFactory, MySql.Data.Entity.EF6">
      <parameters>
        <parameter value="mySqlConnection" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>
  </system.data>
`

and config 

`<DbResourceConfiguration>
      <add key="ConnectionString" value="mySqlConnection" />
      <add key="ResourceTableName" value="Localizations" />
      <add key="AddMissingResources" value="True" />
      <add key="ResxExportProjectType" value="Project" />
      <add key="StronglyTypedGlobalResource" value="~/Properties/Resources.cs" />
      <add key="ResourceBaseNamespace" value="proj.Properties" />
      <add key="ResxBaseFolder" value="~/Properties/" />
      <add key="LocalizationFormWebPath" value="~/LocalizationAdmin/" />
      <add key="BingClientId" value="" />
      <add key="BingClientSecret" value="" />
      <add key="ActiveConfiguration" value="" />
    </DbResourceConfiguration>`

also applied changes to global.asax file

`protected void Application_Start()
        {
            DbResourceConfiguration.Current.DbResourceDataManagerType = typeof(DbResourceMySqlDataManager);
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
            DbResourceConfiguration.Current.ConnectionString = "mySqlConnection";
            DbResourceConfiguration.Current.DbResourceDataManagerType = typeof(DbResourceMySqlDataManager);
        }
        protected void Application_BeginRequest()
        {
            // Automatically set the user's locale to what the browser returns
            // and optionally only allow certain locales/locale-prefixes 
            WebUtils.SetUserLocale(currencySymbol: "$", allowedLocales: "en,ro");
        }`

but still get the same error

**Comment by liviudragnoiu** [comment]
and conn string as 
`<add name="mySqlConnection" connectionString="server=localhost;port=3306;user id=user;password=pwd;database=localizations" providerName="MySql.Data.MySqlClient" />`

**Comment by liviudragnoiu** [comment]
Nothing works I think MySqlDataAcces is missing

**Comment by liviudragnoiu** [comment]
do you have some limitations on mysql connectors or there is a bug?
i cloned solution and did few debug and seems that data.executeReader gives null at first call but at second call i got some data. Where the issue can be?

**Comment by liviudragnoiu** [comment]
in my solution it seems to work without that default and force get provider from connString

@@ -54,7 +54,7 @@ namespace Westwind.Utilities.Data
#endif

        public SqlDataAccess(string connectionString)
            : base(connectionString, SqlClientFactory.Instance)
            : base(connectionString)
        { }

#if NETFULL

**Comment by RickStrahl** [comment]
That code looks like it's hitting the SQL Server provider. Are you shure you're setting hte provider in the configuration?  

If you are running the preview you might want to try this again with the beta. There were a lot of broken bits in the preview related to non-SQL server providers that have now been addressed. Make sure to re-read the configuration section for SQL providers.
