### ISSUE TITLE
Dojo + Westwind Globalization?

### ISSUE THREAD

**Issue by sweco-seurhe** [RickStrahl/Westwind.Globalization#98]
Is there any plans to support the Dojo Toolkit?
We have a couple of Web applications that mix ASP.NET MVC and the Dojo Toolkit [()](http://dojotoolkit.org) . Some of them need localization and we find Westwind Globalization excellent for the .NET part. But Dojo has its own localization that is nice on its own, but without administration. We want to centralize the administration and would like if WWG could take care of the admin of the Dojo part to.
 - Any plans?

**Comment by RickStrahl** [comment]
No not really. We provide a way to serve resources as JSON objects that you can use in your application. If something other than that is required you can certainly extend the functionality along the same lines as the JavaScriptResourceProvider functionality to serve resources in a format that is required by Dojo.

For more info see:
https://github.com/RickStrahl/Westwind.Globalization#javascript-resource-handler
